repos:
  - hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - pre-push
    repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3

  - hooks:
      - id: uv-lock
    repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.4

  - hooks:
      - id: mypy
        additional_dependencies:
          - types-PyYAML
    repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1

  - hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7

  - hooks:
      - id: mdformat
        exclude: "^(.github/|LICENSE.md)"
        additional_dependencies:
          - mdformat-ruff
          - ruff
    repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22

  # - hooks:
  #   - id: shellcheck
  #   repo: https://github.com/shellcheck-py/shellcheck-py
  #   rev: v0.10.0.1

  - hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
