name: Tests
on:
  pull_request:
    paths-ignore:
      - docs/**
      - README.md
  push:
    branches:
      - main
    paths-ignore:
      - docs/**
      - README.md
jobs:
  tests:
    name: ${{ matrix.python }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python: "3.13" }
          - { python: "3.12" }
          - { python: "3.11" }
          - { python: "3.10" }
          - { python: "3.9" }
          - { python: "3.8" }
          - { python: "3.7" }
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v6.4.3
        with:
          enable-cache: true
          prune-cache: false
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ matrix.python }}
      - run: uv run --locked tox run -e ${{ matrix.tox || format('py{0}', matrix.python) }}
