name: Tests
on:
  pull_request:
    paths-ignore:
      - docs/**
      - README.md
  push:
    branches:
      - main
    paths-ignore:
      - docs/**
      - README.md
jobs:
  tests:
    name: ${{ matrix.python }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python: "3.13" }
          - { python: "3.12" }
          - { python: "3.11" }
          - { python: "3.10" }
          - { python: "3.9" }
          - { python: "3.8" }
          - { python: "3.7" }
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: astral-sh/setup-uv@4959332f0f014c5280e7eac8b70c90cb574c9f9b # v6.6.0
        with:
          enable-cache: true
          prune-cache: false
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ matrix.python }}
      - run: uv run --locked tox run -e ${{ matrix.tox || format('py{0}', matrix.python) }}
